### ISSUE TITLE
Mockups rate

### ISSUE THREAD

**Issue by Kejoh** [BC-MAY-21-RN/proyecto-final-proyecto-final-pf-f22-t2#27]
We need to created rate in mockups

**Comment by VaninaWinnik** [comment]
I created the rate Screen design in mockups

![Captura de pantalla de 2022-05-05 17-31-18](https://user-images.githubusercontent.com/97992137/167020761-ee9d7061-6d2a-4572-ac5f-e33279b9f96d.png)
