### ISSUE TITLE
Mockup Food Screen

### ISSUE THREAD

**Issue by w01fgxng** [BC-MAY-21-RN/proyecto-final-proyecto-final-pf-f22-t2#29]

**Comment by Kejoh** [comment]
**DESCRIPTION**
We created the food screen, the list contain:
- Image
- Small description
- Price
When you click in one of them, appear a modal

<img width="708" alt="Screenshot 2022-05-13 at 23 38 43" src="https://user-images.githubusercontent.com/12192868/168392986-9d099eac-dccd-4214-aef2-4f6c40c2e775.png">
